# Credits: https://stackoverflow.com/a/61706020 || https://github.com/SUPERCILEX
on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Request rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          USER_TOKEN: ${{ secrets.ACCESS_TOKEN }}